### ISSUE TITLE
Separate search functionality for dev and docs

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#285]
When you get to a search results page, the bread crumbs say:

Developer Community > Search Results

I would like them to say:

Docs > Search Results

I suspect this is because on the full app, the developer and docs results are together.  I would like to change that so they are together when searched from developer, but just in the docs when searched from docs (possibly with a link to search across docs and developer?).

**Comment by dmcassel** [comment]
@dsokolsky looks like this one is done, right? can we close it?

**Comment by dsokolsky** [comment]
Yes, I am closing it.
