### ISSUE TITLE
link with anchor stays in current page

### ISSUE THREAD

**Issue by innovimax** [marklogic/RunDMC#324]
In docs.marklogic.com/xdmp:eval
For <result>
The link for the second xdmp:spawn example points to http://docs.marklogic.com/xdmp:eval#spawnresultex instead of http://docs.marklogic.com/xdmp:spawn#spawnresultex
[[For an example, see The second xdmp:spawn example. ]]

**Comment by dsokolsky** [comment]
I think this is fixed now.
