### ISSUE TITLE
fr:error() description is ... in error !

### ISSUE THREAD

**Issue by innovimax** [marklogic/RunDMC#331]
In https://docs.marklogic.com/fn/error-and-trace

![capture d ecran 2014-11-06 a 23 55 08](https://cloud.githubusercontent.com/assets/215795/4945734/b80d4c24-660a-11e4-8622-7668b2f3e481.png)

**Comment by dsokolsky** [comment]
Whatever you did, it seems to have worked.  It seems that the notes are now showing up fine.
