### ISSUE TITLE
Description of flexrep:pull-set-name is "."

### ISSUE THREAD

**Issue by innovimax** [marklogic/RunDMC#332]
In https://docs.marklogic.com/flexrep
Description of flexrep:pull-set-name is "."
![capture d ecran 2014-11-07 a 00 34 22](https://cloud.githubusercontent.com/assets/215795/4945945/a9981f4a-660d-11e4-87a7-118126086b99.png)

**Comment by dsokolsky** [comment]
This will be fixed live when we next push docs, so closing this.
