### ISSUE TITLE
RFE: bookmarkable TOC slices

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#343]
One of the disadvantages of the way we handle the navigation panel in the docapp is that I can't bookmark the tabs. 

For example, when I'm working with a client API or XQuery, I don't care about the server-side javascript apidoc that comes up by default, yet I always have to wait for it render. There's nothing wrong with the default choice of the SS JS, just with the fact I can't skip it when it's not germane. 

I realize I can bookmark individual items on each tab, such as the Node.js apidoc and the guide, but then I need 2 bookmarks instead of one. You also don't end up on the relevant tab that way, so you lose the relevant grouping.

Just something for the wishlist. :)

**Comment by gfurbush** [comment]
When I open the docs in Firefox, I see this:
 
![screenshot](https://cloud.githubusercontent.com/assets/2280725/20763706/0923a9e6-b6e0-11e6-9eec-80c7bcc4d416.gif)

**Comment by dmcassel** [comment]
@gfurbush any chance a refresh clears that up? It's looking fine in FF for me.

**Comment by gfurbush** [comment]
No.  Still can't get the pull-down menu:

![image](https://cloud.githubusercontent.com/assets/2280725/20766734/69ce3a20-b6ec-11e6-9ca0-ed34e28f8bb2.png)

**Comment by dmcassel** [comment]
Can you check for JS errors, or other loading problems on the console?

**Comment by paxtonhare** [comment]
@gfurbush which version of firefox and what OS?

**Comment by gfurbush** [comment]
50.0  

Windows 7 Professional

**Comment by kcoleman-marklogic** [comment]
@gfurbush Looks like it might be a browser cacheing problem for you. I did not have FF installed, so I grabbed a copy. It looks fine - the dropdown is there. You'd probably have to do something like what's suggested in the accepted answer to this question in order to clear it up:

http://superuser.com/questions/173210/how-can-i-clear-a-single-site-from-the-cache-in-firefox

@dmcassel One thing I noticed in both Chrome and FF is that there is extra whitespace at the front of the text in the section dropdown. I wouldn't think it's caused by this change, though, so I'll file a separate ticket about it.

**Comment by dmcassel** [comment]
can someone test this in IE?

**Comment by kcoleman-marklogic** [comment]
It looks OK to me in IE 11. None of us can actually exercise the feature since we can't log in, so I hope that's not what the feedback you were looking for.

**Comment by dmcassel** [comment]
If you log on through dmc-stage, you'll also be logged in at docs-stage.

**Comment by kcoleman-marklogic** [comment]
Thanks for your help. I was able to get it working. I was able to set it from Chrome, FF, and IE, and have the change stick across browsers, so it looks like it is work OK.

**Comment by kcoleman-marklogic** [comment]
The new feature seems to be working and, AFAICT, the docs we reloaded are all OK. Version 5 really is version 5, etc.

I found two unrelated problems (#632 and #633), filed separately. #632 is just aethestic fussiness. I'd like to see it fixed, but wouldn't have a conniption if it went live. #633, however, is a blocker for pushing to live.

**Comment by kcoleman-marklogic** [comment]
As you no doubt guessed, I forgot to take another look at this on Friday. Sorry! 

Working on the better late than never plan, it's looking good now. I reviewed it in all three browsers. The feature is working and didn't see any layout issues.

**Comment by dmcassel** [comment]
Great, thank you! Monday I'll merge and deploy.

**Comment by dmcassel** [comment]
Deployed to prod
