### ISSUE TITLE
ninja tutorials broken using https

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#347]
I am transferring this from bugtrack 26278.  

If you go to a ninja tutorial using https, the formatting does not work.  For example:

https://developer.marklogic.com/try/ninja/page2

It works OK on http.  This is because of some kind of cross-scripting problem with the try server.  Dave, I am handing this one off to you.

I am not really sure how to fix it.

**Comment by joemfb** [comment]
This is because https://try.demo.marklogic.com/ is using a self-signed cert.

**Comment by paxtonhare** [comment]
I pushed a fixed for this. I'm now proxying requests to the try server. The trick is we have to deploy an update to the try server at the same time that we deploy this fix.
