### ISSUE TITLE
net-http-digest_auth gem required to deploy_docs

### ISSUE THREAD

**Issue by mariannemyers** [marklogic/RunDMC#359]
The following error is generated when the net-http-digest_auth gem is not installed:
<pre>
<code>
MacPro-2663:RunDMC mmyers$ ./ml local deploy_docs
XSD directory is /Users/mmyers/Library/MarkLogic/Config
ERROR: The net-http-digest_auth gem is required for this feature.
ERROR: Run: $ gem install net-http-digest_auth
</code>
</pre>

Consider adding a note on this requirement to the README.md.

**Comment by dmcassel** [comment]
Addressed by PR #360
