### ISSUE TITLE
Search counts are incorrect

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#363]
Do a search for something with lots of results ("year" -- 140 results). Click on a facet (user guides -- 25 results). 

- the list of results does get narrowed down by the facet selection, but 
- the "<start> to <finish> of <total>" still shows the previous total (140)
- the paging control still assumes the previous total number of pages (14)

**Comment by dsokolsky** [comment]
Mike, this can be part of what you look at with the search stuff I am interested in.  This part might be life, not sure (although the second and third bullets above seem like we can do something about them).

**Comment by mblakele** [comment]
I'm pretty sure we have both numbers available. I noticed this behavior myself and decided it was by design, but maybe I misunderstood the code history.

**Comment by dsokolsky** [comment]
This looks correct on the doc-only side now.  I have not looked at the combined dev and doc side.

**Comment by dmcassel** [comment]
Verified that this is working properly.
