### ISSUE TITLE
Missing version widget on API search results page

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#366]
When searching API docs only with `api=1`, the `version_list` select widget does not display.

**Comment by dsokolsky** [comment]
The version widget does not seem to be working anymore--I am (maybe incorrectly) assuming it is because of this change.  To repro, just try from any page (including the home page) to select another version.  It try to load that page in the selected version, but it does not.

**Comment by mblakele** [comment]
No, it's more recent: bad conflict resolution after pulling from master.

**Comment by dsokolsky** [comment]
I think this is working properly now.
