### ISSUE TITLE
hierarchical facets for guides and functions

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#369]
In addition to the existing facets, search results should show another level of child facets for function pages (by language) and guides (by book name). This will probably extend the existing collection name mechanism.

Search should support selection of multiple facets, but UI is optional for the first implementation.

**Comment by mblakele** [comment]
On UI for multiple selections, http://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php has some good discussion.

I'd rather not use checkboxes. Categories are hierarchical, so maybe we could get by with saying that facets accumulate in an OR until reset by a click on "All categories"? Each category or subcat would also act like a toggle, so a second click on a selected category would unselect it. We would also automatically unselect any categories that have subcategories selected, or else the subcategory selection wouldn't mean anything. So if a query includes `cat:guide` and I select `cat:guide/admin` then the final query will only have `cat:guide/admin`.

I think that's practical to implement. But would behavior like that surprise users who aren't expecting multi-select at all?

**Comment by mblakele** [comment]
UI is ready for testing. I think it's fairly discoverable for desktop users, but mobile may need more work.

**Comment by dsokolsky** [comment]
I think this is good.  Some day we might tweak the UX on it but overall I really like it.
