### ISSUE TITLE
typeahead search suggestions

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#371]
When users type into the search input element, suggest matches from:

* function names
* guide chapter titles
* message codes

**Comment by mblakele** [comment]
I still want to add support for arrow keys, but this should be testable.

**Comment by dsokolsky** [comment]
Mike, I imagine I need to make some index changes to make this work....what indexes do I need to add?

**Comment by mblakele** [comment]
This might be a good time to use roxy: `./ml <envname> bootstrap` will deploy everything from `deploy/ml-config.xml`, which has the index definitions. If that doesn't suit you, you can copy the element range index config from that file: look for `<localname>suggest</localname>`.

**Comment by dsokolsky** [comment]
One problem I see is that it seems to be searching across version in the suggest box--I think it should pass in the version.  For example, try typing:

xdmp.zip

Under MarkLogic 7, you will see entries for xdmp.zipcreate, zipget, and zipmanifest.  But those are only there in 8.

Also, the arrow key support will be good to add.

I like the element-word-query custom constraint you made--that is clever.

**Comment by dsokolsky** [comment]
I am going to call this done.  Anything else we see can be a separate bug.
