### ISSUE TITLE
camelCase keys option for apidoc:usage schema handling

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#378]
OK, this will be a little bit of a pain.  Sigh.

We have made the output of *some* of our js builtins that return schema-defined output to camel case.  The problem is, we have not done it for all.  So what we need is the ability to add an option to the apidoc:usage markup that says ``camelCase="true"`` or something like that, where it defaults to false if the attr is not there.

An example is xdmp.forestStatus. 

It looks like ``stp:fixup-children-apidoc-usage`` is where the code for this is, in apidoc/setup/setup.xqm.

What I would like is for it to camelCase the names pulled from schema (using the same rules we use for the apis) when ``camelCase="true"`` is present in the markup (similar to how it does the processing if ``apidoc:usage/@schema`` is there).

So this should not change anything unless we change the markup in the source.

Let me know if this does not make sense.

**Comment by mblakele** [comment]
I'd prefer to call the new attribute `camel-case` instead of `camelCase`, for consistency with the rest of the XML.

What about functions that don't use schema to populate usage? One example is `xdmp.queryMeters`.

**Comment by dsokolsky** [comment]
I'm fine making the name camel-case in the xml.

As far as xdmp.queryMeters, probably the right thing is to (someday) make that use the schema.  For now, I am going to ignore that.

**Comment by dsokolsky** [comment]
I added camel-case="true" to forest-status so we'll see tomorrow if that works.

**Comment by dsokolsky** [comment]
I probably did not make it clear that when it says camel-case="true", it should only do the camelCase on the JavaScript side--the XQuery side should still be like the schema.  Looking quickly at the code,  I am not sure if it does that.

**Comment by dsokolsky** [comment]
The camelCase is working, but it is being applied to both xquery and javascript.  It needs to apply just to javascript.

**Comment by mblakele** [comment]
I'm not seeing it. After a clean rebuild with this morning's zip, `/8.0/xdmp.forestStatus` shows camel and `/8.0/xdmp:forest-status` does not — both as expected.

Are you sure you also picked up 5736d2f?

**Comment by dsokolsky** [comment]
I did miss that one, sorry.  After updating and reloading, all is well.  Thanks Mike.  We're calling this one done.
