### ISSUE TITLE
back button having problems with hash tag anchors from guides

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#379]
I'm not sure when this started, but I think recently (maybe as a result of #368 ?).  Here is one way to repro it:

1) /8.0/guide/app-dev/appdev#id_10659
2) click on any of the links to other guides on the page.
3) click the back button.  

It takes you back to the top of the page (although the url looks to have the hash anchor in it).

I have seen similar behavior clicking on a link to a function from a guide as well, and I have seen some instances of it not  displaying the guide page (although the url looks right).  But I cannot consistently repro this part.

**Comment by mblakele** [comment]
Did this ever work? If so, any idea when it broke?

**Comment by dsokolsky** [comment]
I am not sure.  It seems like it used to work.  I was thinking #368 might have been the trigger for it breaking, but that is a total guess.  But it does not work on docs either, so it is certainly possible this never worked.

**Comment by mblakele** [comment]
Doesn't seem to work on docs either. For firefox at least, it might be https://bugzilla.mozilla.org/show_bug.cgi?id=565008 — we are using what that bug calls "css frames", so that would apply. It would probably work as expected if we could get away from using a scrollable sub-area for the content, but I don't know how likely that is.

**Comment by dsokolsky** [comment]
It is fine to put this on the back burner.

**Comment by mblakele** [comment]
If we can detect the back button, do you want to force scrolling? That may do unexpected things if the user really did move around, but I think we could do it.

**Comment by dsokolsky** [comment]
Yes, I would like to force scrolling on the back button for these links.  I am OK with the unexpectedness if they have scrolled around.  So if this is possible and not too hard, it would be nice.

**Comment by dsokolsky** [comment]
looks good to me.
