### ISSUE TITLE
provide a way to "unhighlight"

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#380]
Before the fix for #368, you could reload the page to remove the highlighting.  Now, you have to actually hack the url and remove the request parameter and value.

IWBNI there was some way to unhighlight it.  I wish I had a brilliant idea for how to do that, but I don't--could be some sort of button that only shows up when highlighting is happening?

I think where this comes into play most is when you use the link to send off somewhere.  Then the recipient gets a link with highlights.

**Comment by dsokolsky** [comment]
This seems to have the right functionality, but the button is not in a place where it is very useful because it usually will be scrolled off the screen.  Here is an idea, not sure it is feasible:

Can we put the link in the same screen real estate where the breadcrumbs are, only right-justified (where the breadcrumbs are left-justified).  It is OK if the font is small like the breadcrumbs,  What do you think?

**Comment by mblakele** [comment]
Not without pretty major surgery to the CSS layout styles.

**Comment by mblakele** [comment]
This seems to be as close as I can get.

**Comment by dsokolsky** [comment]
This is much better.  I think the basic interface is good.  

My only complaint that it is a little too in your face.  Can we make it the same font size as the breadcrumbs?

**Comment by mblakele** [comment]
I tend to think the breadcrumb text is a little too small, and we ought to use 12px as a minimum. But this is toned down a little, and the CSS should be easy to tweak.

**Comment by dsokolsky** [comment]
This is better.  Let's call this done and if we come up with any other UI tweaks we can consider those as separate problems.  Thanks Mike.
