### ISSUE TITLE
map xquery param map:map to Object

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#384]
We currently seem to be mapping map:map* parameters to String[] (and presumably map:map to String).

These should both be mapped to Object (or Object* I guess for the * case).

The only function I know that this effects now is sem.sparqlValues.  But it will be more important in the future (especially if we start to doc xquery library functions).

This is only for parameters, not for return types.

**Comment by mblakele** [comment]
Wouldn't that be `Object[]` instead of `Object*`? Existing code maps `xs:string*` to `String[]`, for example.

Let's try mapping any `*` or `+` param that isn't already special-cased to its normal type mapping plus `[]`, and see how that goes. It doesn't break any test cases.

**Comment by dsokolsky** [comment]
I think ``[]`` will be OK.  That seems to at least work in that function.

**Comment by dsokolsky** [comment]
Fixed, thanks.
