### ISSUE TITLE
(1) Home Page: Update H1 & H2 Color

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#385]
Can we update the H1 and H2 to be #191919.

The reasons why this is a 1 priority:
- We want the h1 to be a main focal point on the page and by having it as lighter gray it is blending in.
- We want to start to turn the boat to be more consistent with the www site.

![screen shot 2015-01-23 at 1 05 23 pm](https://cloud.githubusercontent.com/assets/4975480/5882696/89bc5152-a300-11e4-9f9b-3dacd4308669.png)

![screen shot 2015-01-23 at 1 00 43 pm](https://cloud.githubusercontent.com/assets/4975480/5882683/71018b00-a300-11e4-97a1-aead42d2fd34.png)

![screen shot 2015-01-23 at 1 00 50 pm](https://cloud.githubusercontent.com/assets/4975480/5882685/75320268-a300-11e4-899d-d3438a512c22.png)

**Comment by dmcassel** [comment]
done, deployed to stage
