### ISSUE TITLE
(1) 15px Left and Right Padding On .home.container-fluid

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#390]
(1) 15px Left and Right Padding On .home.container-fluid

CSS
```
.container-fluid {
  padding-right: 0px;
  padding-left: 0px;
  margin-right: auto;
  margin-left: auto;
}
```

![screen shot 2015-01-23 at 1 38 35 pm](https://cloud.githubusercontent.com/assets/4975480/5883223/370a4306-a305-11e4-9342-2bb4e77ec206.png)

![screen shot 2015-01-23 at 1 38 40 pm](https://cloud.githubusercontent.com/assets/4975480/5883227/39542802-a305-11e4-9d1d-5cb472b28f29.png)

**Comment by dmcassel** [comment]
deployed to stage
