### ISSUE TITLE
(1)  Remove extra HR on home page after New Features

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#391]
There is a HR between the "new features" and bottom 4 columns... (See below)
Can we remove that and just use the CSS borders?

![screen shot 2015-01-23 at 1 41 44 pm](https://cloud.githubusercontent.com/assets/4975480/5883289/f187eb8e-a305-11e4-94da-da16ead9b09e.png)

![screen shot 2015-01-23 at 1 41 36 pm](https://cloud.githubusercontent.com/assets/4975480/5883294/f5ce47f6-a305-11e4-8630-0d4568e5f429.png)

![screen shot 2015-01-23 at 1 41 57 pm](https://cloud.githubusercontent.com/assets/4975480/5883300/fc727afa-a305-11e4-803a-055822cb7112.png)

**Comment by dmcassel** [comment]
deployed to stage
