### ISSUE TITLE
(1) Remove extra HR on home page after 4 columns

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#392]
Can we remove extra HR on home page after 4 columns and use the CSS borders?  We may need to add padding... I will submit in a separate ticket...

![screen shot 2015-01-23 at 1 49 58 pm](https://cloud.githubusercontent.com/assets/4975480/5883409/e40dd698-a306-11e4-9f84-3cc3e8840fa4.png)

![screen shot 2015-01-23 at 1 50 09 pm](https://cloud.githubusercontent.com/assets/4975480/5883411/e61cabee-a306-11e4-8795-489b3a1b0c75.png)

**Comment by dmcassel** [comment]
deployed to stage
