### ISSUE TITLE
(1) Remove Gray background color on #content

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#393]
On the home page can we change the gray background color on #content div tag to #fff?
It is creating a small gray stripe on the bottom of the page...

![screen shot 2015-01-23 at 2 00 09 pm](https://cloud.githubusercontent.com/assets/4975480/5883534/350e518e-a308-11e4-82e4-fba0d1c3dc5b.png)

![screen shot 2015-01-23 at 1 53 59 pm](https://cloud.githubusercontent.com/assets/4975480/5883471/87d227c0-a307-11e4-8e32-8abbafdded36.png)

**Comment by dmcassel** [comment]
deployed to stage
