### ISSUE TITLE
(1) Add 3rem; top and bottom padding to "connect" button 

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#394]
Can we add a 3rem; padding around the "connect" at the bottom of the page?

CSS
```
.page-cta-wrapper {
  padding-top: 3rem;
  padding-bottom: 3rem;
}
```

HTML
```
<div class="row page-cta-wrapper">
      <a href="/mailman/listinfo/general" class="btn btn-default col-md-4 col-md-offset-4 col-xs-12">Connect: Join the Developer List</a>
</div>
```
![screen shot 2015-01-23 at 1 53 59 pm](https://cloud.githubusercontent.com/assets/4975480/5883554/64614842-a308-11e4-8aeb-ee0e7e11ba75.png)

![screen shot 2015-01-23 at 2 02 30 pm](https://cloud.githubusercontent.com/assets/4975480/5883597/bf993634-a308-11e4-8c9f-a38e5fff63c3.png)

![screen shot 2015-01-23 at 2 06 12 pm](https://cloud.githubusercontent.com/assets/4975480/5883621/0b13bfe4-a309-11e4-858c-42d581c35370.png)

**Comment by dmcassel** [comment]
deployed to stage
