### ISSUE TITLE
extra text showing up next to the "previous" button in to of guide pages

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#395]
Here is an example:

/8.0/guide/app-dev/triggers

This has "applicationdevelopersguideusingtriggersspawnactions" to the right of the previous button.

This appears to come from the suggest, as the source to this page looks like this:

``<api:suggest xmlns:api="http://marklogic.com/rundmc/api">application</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">developer</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">s</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">guide</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">using</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">triggers</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">spawn</api:suggest><api:suggest xmlns:api="http://marklogic.com/rundmc/api">actions</api:suggest>``

**Comment by dsokolsky** [comment]
Or do I have to redeploy/update my config?

**Comment by mblakele** [comment]
Looks like 20b28a1179dc806908792c244e6929b5a7dd7c34 missed this case.

**Comment by dsokolsky** [comment]
seems fixed now.
