### ISSUE TITLE
(1) Update 4 column images on homepage

### ISSUE THREAD

**Issue by heymattallen** [marklogic/RunDMC#400]
Replacement images that Steve sent...
![amazon](https://cloud.githubusercontent.com/assets/3708649/5943795/d3b97b02-a6d6-11e4-9c91-1dfdcf40a145.png)
![qconsole-javascript](https://cloud.githubusercontent.com/assets/3708649/5943796/d3ba5bee-a6d6-11e4-95c8-ffdbc47ee649.png)
![samplestack-screenshot](https://cloud.githubusercontent.com/assets/3708649/5943798/d3bcec92-a6d6-11e4-8e03-dafdf363abc6.png)
![semantics](https://cloud.githubusercontent.com/assets/3708649/5943797/d3ba97bc-a6d6-11e4-983e-b4dd2b06c05e.png)

**Comment by dmcassel** [comment]
deployed to dmc-stage
