### ISSUE TITLE
Amazon Link On Home page

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#403]
Hi Dave, 
Diane Burly was wondering why we are linking to a different amazon page on the download pages verse the link on the home page...  From a user experience perspective she seemed a confused by this.  

Home page link: http://docs-stage.marklogic.com/guide/ec2/GettingStarted
DL page link:  http://dmc-stage.marklogic.com/products/aws

**Comment by stephen-gehring-ml** [comment]
hahaha I accidentally types "Hi Dave" in the title  =O)

**Comment by heymattallen** [comment]
I think the Amazon link on the homepage should go here: "/products/aws" rather than to the docs page.

**Comment by dmcassel** [comment]
Works for me.

**Comment by dsokolsky** [comment]
Is this done?  If so, can you please close it.
