### ISSUE TITLE
(2) Update Node tutorial title, intro and side bar nav

### ISSUE THREAD

**Issue by heymattallen** [marklogic/RunDMC#413]
For the tutorial on node (http://dmc-stage.marklogic.com/learn/node-client-api), need to update the title on the tutorial page to say "Getting Started with the Node.js Client API" rather than "Node.js Client API Getting Started" and remove it from the list of "Other Tutorials" so it's not lsited twice. 

Need to remove the language at the top of the page that says

"
Justin Makeig
Last updated 
"

Also, the page looks like draft without a sidebar - is there anything we can do to update the sidebar (perhaps referencing different sub-sections of the tutorial as we do with other tutorials?

**Comment by dmcassel** [comment]
Looks like someone has already updated the title.

**Comment by dmcassel** [comment]
I figured out why the "last updated" date wasn't displaying and I fixed that. I think there is value in showing that information, so I'm inclined to keep it. I don't have strong feelings about the author for the tutorial. We display it for [other tutorials](http://developer.marklogic.com/learn/java). 

Looking into the sidebar thing.

**Comment by dmcassel** [comment]
fixed the sidebar

**Comment by dmcassel** [comment]
Regarding the Other Tutorials list, there are a number of them listed twice. Seems to be based on the type of document used to store content in the database, rather than a constructed list. I'll write up a separate ticket for that.
