### ISSUE TITLE
OK to delete old branch "new-styles"?

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#417]
@dmcassel @dsokolsky https://github.com/marklogic/RunDMC/tree/new-styles looks pretty old. I don't think we'd want anything from it, but I thought I'd check before deleting it. Please speak up if you'd rather I leave it alone.

**Comment by dmcassel** [comment]
I'm not aware of anything useful in it.

**Comment by dsokolsky** [comment]
This stuff is all obsolete.  Delete away.
