### ISSUE TITLE
TOC filter doesn't always work on XQuery API reference tab

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#419]
I frequently have problems with the TOC filter behaving incorrectly when I try to use it on the XQuery APIs. My perception is that it is because the filter accepts input before the TOC is actually ready. That is, I think I only run into this when I have just switched tabs. For example, from Guides to Server-Side XQuery APIs. When I want to find something, I tend to switch tabs and immediately start typing into the filter box.

I've observed 2 kinds of failures, but I think they're both the same problem, just timed differently.
- Switch to the XQuery tab and immediately enter a search term in the filter. I see the filtered results briefly, but then they are replaced with the full TOC (unfiltered).
- Switch to the XQuery tab, wait very briefly, then filter. You get filtered results from the "by category" grouping, but unfiltered results from the "by name" grouping.

(I'm using "filtered" here in the sense of whether or not my TOC filter has been applied, not in the MarkLogic "filtered query" sense.)

Both those behavior feel like a timing problem to me.

**Comment by dmcassel** [comment]
I see this sometimes but haven't been able to reproduce it consistently enough to file. Danny, I showed you this when last time I was at HQ.

**Comment by mblakele** [comment]
When this happens can you check the console and see if there are any messages? So far I haven't been able to reproduce, but any additional details may help.

**Comment by kcoleman-marklogic** [comment]
Naturally, today I can't get it to reproduce on demand (sigh) as the TOC is rendering quite briskly. I'll try to remember to leave the console up for a few days and see if I can catch it in the act. Stay tuned.

**Comment by kcoleman-marklogic** [comment]
Finally managed to provoke this again while I had the developer tools up in Chrome. No joy. There are no errors or any other messages in the console. The exact steps this afternoon were:
- New browser session - first time I had hit pubs since a reboot
- Went to http://pubs.marklogic.com:8011/
- Clicked on the XQuery tab and typed "suggest" into the filter

FWIW, it's been harder to get it to happen this week. I thought maybe it was gone, but it bit me twice today. Purty pitchers below, in case it's of some use.

When it's working properly, you get this:
![ok](https://cloud.githubusercontent.com/assets/1951367/6070994/52d6b7fe-ad46-11e4-96df-214a48ab3d9b.jpg)

When it's being a troll, you get something like this, with every function in universe showing in the By Name section at the bottom. I elided some collapsed categories and the like. They're present, just not expanded.

![bad](https://cloud.githubusercontent.com/assets/1951367/6071110/52690758-ad47-11e4-8caf-025765646fbe.jpg)

**Comment by mblakele** [comment]
I'm still unable to reproduce this so I don't have much confidence that this will help. But it may produce some console messages.

**Comment by kcoleman-marklogic** [comment]
Still happens to me frequently and is driving me slowly insane. Still no console messages, either.

How do I enable the debug level logging from docapp's JS? I can see the LOG.debug calls in the code, but they're clearly not enabled in my env. I want it to talk to me!

**Comment by mblakele** [comment]
Try `LOG.DEBUG = true` in the console.

**Comment by kcoleman-marklogic** [comment]
That works, thanks. Unfortunately, it didn't yield anything useful that I could see. (Not that have a clue what I'm doing.) 

The most I can say is that what gets passed in the tocRoot parameter of loadAllSubSections is different in the working and non-working case. i.e. one has the filter matches in it, and the other has everything. But you probably knew that already.

Tidbits gleaned from deliberately provoking this bug:
- It is easy for me to make this happen, but only the first time I hit the XQuery function list. 
- I can't do it with any of the other tabs, perhaps because they're all a lot shorter. 
- It's quite common to see the correct results very briefly before they get overwritten with the unfiltered output.
- How long you wait after switching to the XQuery tab is irrelevant.

Maybe next time you're at HQ, you can look over my shoulder, Mike. IDK what else to suggest.

Here's some of the debug output. I doubt it's of any use, though.
```
 TOC select option changed
rundmc_init.js:15 TOC select option changed to n4922eb221c02c95e
rundmc_init.js:15 filter-close-button click f.Event {type: "click", timeStamp: 1425688294080, jQuery17206603365370538086: true, isTrigger: true, exclusive: undefined…}
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:34 GMT-0800 (Pacific Standard Time) 
rundmc_init.js:15 filter idle Fri Mar 06 2015 16:31:34 GMT-0800 (Pacific Standard Time) 
rundmc_init.js:15 filterConfigDetails  .apidoc_tree:visible
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:38 GMT-0800 (Pacific Standard Time) s
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:38 GMT-0800 (Pacific Standard Time) su
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:38 GMT-0800 (Pacific Standard Time) sug
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:38 GMT-0800 (Pacific Standard Time) sugg
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:39 GMT-0800 (Pacific Standard Time) sugges
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:39 GMT-0800 (Pacific Standard Time) sugges
rundmc_init.js:15 filter not idle Fri Mar 06 2015 16:31:39 GMT-0800 (Pacific Standard Time) suggest
rundmc_init.js:15 filter idle Fri Mar 06 2015 16:31:40 GMT-0800 (Pacific Standard Time) suggest
rundmc_init.js:15 filterConfigDetails suggest .apidoc_tree:visible
rundmc_init.js:15 loadAllSubSections [ul#n4922eb221c02c95e.treeview.apidoc_tree, prevObject: e.fn.e.init[1], context: document, selector: ".apidoc_tree:visible", constructor: function, init: function…]
rundmc_init.js:15 loadTocSection 0 1 true
rundmc_init.js:15 loadTocSection 1 1 true
rundmc_init.js:15 loadTocSection 2 1 true
...and many more loadTocSection calls...
scrollTOC scrollTo 0
```

**Comment by kcoleman-marklogic** [comment]
As near as I can tell, this change is working. It leads to a longish (2-5s) period during which the app appears to not be responding to the filter, but only when the TOC is "cold". 

Ideally, maybe, there'd be a spinny cursor during that period, but IDK how well that would interact with other things, like if you immediately wanted click on one of the links on the landing page on the right instead of interact with the TOC.

I did see one bad behavior that felt related, but maybe isn't: 

Instead of interacting with the toc, I flipped to the Guides section, collapsed everything (as usual), expanded the developer guides section, and then clicked on the search dev guide. There was a several second delay before the guide's landing page came up. 

I am guessing this was while the guides TOC was finishing loading, but IDK. I haven't been able to get it to do it again, so maybe it was gamma rays.

**Comment by dmcassel** [comment]
@kcoleman-marklogic on the cold response, that may be what should happen. The TOC is a 1.6MB download, which then needs to be inserted into the DOM. Do you see that delay if you go to the page, wait a few seconds, and then type in the filter, or only if you start typing quickly?

**Comment by kcoleman-marklogic** [comment]
Agreed that the delay is probably expected behavior. I think it is acceptable.

I cannot get it to do it today, with or without a delay. Maybe it has more to do  with the server cache than client, in which case it is obviously of no concern at all.

**Comment by dmcassel** [comment]
I think the long-term fix to that delay is that we shouldn't load all 1.6MB at a time; rather, load them by section. Of course, that's a pretty involved change.

**Comment by dmcassel** [comment]
deployed latest attempt to prod. let's see what happens
