### ISSUE TITLE
DMC additions/changes for 8.0-1

### ISSUE THREAD

**Issue by gvaidees** [marklogic/RunDMC#425]
Here is a list of things that we need to add/change in DMC for 8.0-1. I am listing the items and owners you should contact 

1. A new page for Samplestack. @sudo-jmakeig and Kasey are the contact for providing this content and where it falls from navigation standpoint
2. A new page for Node.JS client. @sudo-jmakeig is the contact for providing this content. I believe this needs to be at the same level as Java Client API from navigation standpoint. The structure of this page should be similar to Java client APIs page. However, we will not have any download section. 
3. Update the Java Client API page as follows 
  - Provide a link to github java client api project - @sudo-jmakeig to provide the blurb
  - @sudo-jmakeig may also provide you additional content for this page to be added to features section
  - In http://developer.marklogic.com/products/java, 
      - Remove the Maven --> Repository section.
      - In Maven --> Dependency section, change the version-id to be <b>3.0.1</b>
      - In Downloads section, we will also have a link for 3.0-1 Java client zip and source. The link name is Release 3.0-1 zip package (compatible with Version 8 server). We will provide you the zip and source for upload to DMC
4.For other changes, it might be easier if we got together on a phone and I can tell you the changes and you can tell me how to do those changes. Or we can do them together via webex

**Comment by gvaidees** [comment]
For other changes, it might be easier if we got together on a phone and I can tell you the changes and you can tell me how to do those changes. Or we can do them together via webex

**Comment by dmcassel** [comment]
[Samplestack has a page](http://dmc-stage.marklogic.com/features/samplestack), linked from the home page. Am intending to expand the [Samplestack Tools](http://dmc-stage.marklogic.com/code/samplestack) page with some of the content from the features page.

**Comment by dmcassel** [comment]
[Node.js Client API has a page](http://dmc-stage.marklogic.com/features/node-client-api), linked from the home page and the Tools page.

**Comment by dmcassel** [comment]
@gvaidees, Should the Maven -> Repository section be removed everywhere (Hadoop, Java, MLCP, XCC) or just for the Java API?

**Comment by jmakeig** [comment]
Only the Java Client API is in Maven as of the 8.0-1 release milestone. Since we continue to distribute the older version (2.x), we'll still need the custom repo instructions.

**Comment by jmakeig** [comment]
I've updated the [Node.js Client products page in staging](http://dmc-stage-admin.marklogic.com/pages/edit?~doc_path=/products/node.xml).

@dmcassel can you please provide outbound links in the “Tutorials and Samples” section (I’ve got a `<!-- TODO -->` placeholder there for now) and any inbound links from elsewhere?

**Comment by jmakeig** [comment]
@dmcassel, do you have the lock on the `/products/java` content? Let me know if you need something from me.

**Comment by gvaidees** [comment]
@dmcassel Additional updates - 

1. For 6.0 and 7.0 Java APis section, bring back pointers to DMC maven repo
2. Remove mlcp for HortonWorks section from http://dmc-stage.marklogic.com/products/mlcp
3. Remove mlcp-Hadoop1 maven dependency
4. Let us talk to see if we need maven dependency section for "Downloads for MarkLogic 7" under http://dmc-stage.marklogic.com/products/hadoop (to be consistent with mlcp)

Let me know if you want to do this via webex.. thx

**Comment by dmcassel** [comment]
Added inbound and outbound locks for the Node.js product page. Thanks, @jmakeig.

**Comment by dmcassel** [comment]
@gvaidees all requested changes made; please review.

**Comment by gvaidees** [comment]
Thanks @dmcassel for making the changes. Under http://dmc-stage.marklogic.com/products/java, the version of our package should have all dots, such as 2.0.4, 3.0.1 and not 2.0-4. Other changes look good.

**Comment by dmcassel** [comment]
@gvaidees I changed those hyphens to dots. Should be good now.

**Comment by gvaidees** [comment]
@dmcassel Thx. One more minor change - WHen I click on "Java API" under Downloads, it takes me to bottom of the page. Not sure why

**Comment by dmcassel** [comment]
@gvaidees I see that, too. Jumps to different places on Chrome & Firefox, even after clearing history. Doesn't jump in Safari. I have no idea why that's happening.

**Comment by gvaidees** [comment]
@dmcassel not important to get done on 8.0-1. Thx
