### ISSUE TITLE
naming issues and links on Node page

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#428]
I was just randomly looking at this page:
/features/node-client-api

and here are some things I see:

* In the downloads link, I think "Java API" should be "Java Client API"
* In the downloads link, I think "Node Client API" should be "Node.js Client API"
* The title of the page should be "MarkLogic Node.js Client API"  (Node.js, not Node)
* Many of the links point to pubs.marklogic.com:8011 -- those should be changed to docs.marklogic.com  (some are correct, but most are not)

**Comment by heymattallen** [comment]
good catch, Im looking at some of the other new pages as well, I found similar issues on the samplestack page

**Comment by dmcassel** [comment]
Fixed, thanks.

**Comment by heymattallen** [comment]
Also, I thought the link from the homepage for Node.js Client API would take you to a page alongside the other features, but now it takes you to a different section (tools) that is separate from all the other new features pages. It would be a better user experience to have the node page setup like the other feature pages. Then, we copy some or all of the content to the tools page on Node.js. Ping me if Im not making sense.

**Comment by dmcassel** [comment]
@jmakeig just made a /products/node page that I'll link to from the downloads page.
