### ISSUE TITLE
(1) Server-side JS link issue

### ISSUE THREAD

**Issue by heymattallen** [marklogic/RunDMC#430]
the link to download the query console workspace at the top of the page is broken (currently links to a local download) - may need to coordinate with Tanya or Justin to fix this.
http://dmc-stage.marklogic.com/features/javascript

**Comment by heymattallen** [comment]
Also, this link...  "(see “Iterators” below)"   on that same page

**Comment by heymattallen** [comment]
And... "(See Example 3 below.) "

**Comment by dmcassel** [comment]
fixed, thanks
