### ISSUE TITLE
Login email field is case sensitive

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#442]
the login email field is case sensitive and will fail if there’s a mismatch. E.G. I tried to login as Frank.Sanders@marklogic.com and it failed, however frank.sanders@marklogic.com works.

**Comment by dmcassel** [comment]
I've had two requests at community-requests about this recently.

**Comment by dsokolsky** [comment]
I wonder if we just lower-cased both the stored name and the typed in name if that would Just Work.

**Comment by dmcassel** [comment]
That's the simplest solution and seems like it ought to work. Just need to get time to test that.
