### ISSUE TITLE
Response formatting broken

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#445]
On http://developer.marklogic.com/try/ninja/page12, the response you get from the first Run button has some weird formatting, showing some diffs.

**Comment by dsokolsky** [comment]
This is likely the thing where it works if using http, but does not when using https.  This is a long-standing issue if that is what it is.

**Comment by dmcassel** [comment]
Thanks, I'll check into that.

**Comment by dsokolsky** [comment]
See #347

**Comment by dmcassel** [comment]
This does not appear to be the https problem.

**Comment by dmcassel** [comment]
Turned out to just be a crappy looking document. I changed the query to something that looks nicer.
