### ISSUE TITLE
text with non-default char format in text blocks disappears

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#449]
Jane noticed that text in a code block that is bold is disappearing. Not just the formatting, the content. In researching it together, we found the same thing is happening to italics. It seems specific to standalone code blocks (code paragraph style). I have instances in table cells that use the CodeLeft paragraph style which are still working fine.

For example, the first code block at http://docs.marklogic.com/guide/rest-dev/documents#id_65730 renders fine on DMC. It looks like this, except that the value of each property is in italics:
```
{
  "insert": {
    "context": path-expr,
    "position": pos-selector,
    "content": new-content,
    "cardinality": occurrence
  }
}
```
If you look at the same block on pubs, it is very much not fine. The italicized text is gone, apparently replaced by newlines. Like this:
```
{
  "insert": {
    "context": 
,
    "position": 
,
    "content": 
,
    "cardinality": 
  }
}
```
Jane observed the same issue with bold. One example is here: http://pubs.marklogic.com:8011/7.0/guide/semantics/intro#id_32716. On the second line, you see only a lone left bracket, but it should be followed by bolded `sem:triple` text: `<sem:triple...`

The following is an example of the table cell CodeLeft usage that is working properly. See right column of the table here: http://pubs.marklogic.com:8011/guide/rest-dev/documents#id_28242.

**Comment by kcoleman-marklogic** [comment]
P.S. It's definitely not a problem in the FM input because it's rendering properly in the PDFs and on DMC, and at least some of those examples are unchanged between now and the push to DMC for ML8.

**Comment by dsokolsky** [comment]
Probably more fallout from #424.

**Comment by kcoleman-marklogic** [comment]
Jane and I both checked over our respective content, and it looks good now. Thanks!
