### ISSUE TITLE
dmc pages loading very slowly when on VPN

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#450]
Sorry, Dave, this might be a purely operational issue that should go to IT, but I'm going to start with you because I'm ignorant of how DMC is administered or what the heck marketo is.

I noticed today that when I VPN in from home, navigating among pages on DMC is extremely slow, say 15-20s per page. I can make the problem magically go away by simply disconnecting from VPN. It manifests slightly differently on docs.marklogic.com vs. developer.marklogic.com, but both point the finger at marketo. Could be a transient issue, but I thought I should report it somewhere. God knows I'll forget about it by tomorrow...

It doesn't happen to a page you go to directly by URL. It only happens when you subsequently navigate within the site. For example, if  I paste http://developer.marklogic.com/features/bitemporal into my browser, the page comes up immediately. However, if I then click on one of the "Features" links on the left, it takes forever to load. Docs.marklogic.com is behaving the same way when you click on the nav TOC.

I'll attach a couple screenshots from the chrome tools, in case that's of use. It is not browser specifc; I can repro w FF. I'm VPN'd in via Shrewsoft.

**Comment by kcoleman-marklogic** [comment]
From navigating to http://developer.marklogic.com/features/java-client-api.

![dmc_lag1](https://cloud.githubusercontent.com/assets/1951367/6278114/01cdf2a6-b849-11e4-84b8-0ff7848f39e4.jpg)

**Comment by kcoleman-marklogic** [comment]
From nav'ing within docs.marklogic.com. It's easier to look at because the flow is much simpler.

![dmc_lag2](https://cloud.githubusercontent.com/assets/1951367/6278191/b2acf108-b849-11e4-825c-9aed6d6b0986.jpg)

**Comment by kcoleman-marklogic** [comment]
Gory details from failed GET request on the above request.
![dmc_lag3](https://cloud.githubusercontent.com/assets/1951367/6278223/0ef2406c-b84a-11e4-8c78-ba1e3ba06cb4.jpg)

**Comment by dmcassel** [comment]
Interesting. I'm not able to reproduce this -- pages load quickly whether I'm on the VPN or not. Are you still seeing the problem?

**Comment by kcoleman-marklogic** [comment]
Seems to be fine today. The marketo callouts are only taking 56ms. Closing.
