### ISSUE TITLE
some users report slow toc loading

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#453]
A few people have reported slow toc loads, usually they report 10-20 seconds of "hanging".  It has been hard to reproduce this, but we have a few ideas of how to deal with it, so this bug is to track those.

It seems the problems are worse on IE, and to a lesser extent Chrome.  Firefox seems to have the least problems.  Here is some stuff from an email conversation between me and Mike:

Caching may be one reason why IE and Chrome users are reporting more problems than Firefox users. We don't explicitly set any cache headers, but we should be setting Last-Modifed and Firefox uses that as a hint. I'm not sure if IE or Chrome do. I could do some testing, and if necessary figure out how to ensure caching by those browsers. In theory we can say that the TOC content never expires, because it has a new timestamped URL every time we generate it.

I also have some ideas for rebuilding the TOC as a more lightweight structure, and doing the on-demand part more efficiently. Right now all the top-level sections load in the first request in initially-open state. But most users probably don't switch sections, so that's wasted work. The async loads end up only helping the initially closed sections, which isn't as helpful. I'd like to load just the section names and ids initially, and fill in the current section asynchronously.

Unfortunately that's difficult to reconcile with the way the TOC finds the initially selected section. I have some ideas for restructuring that too, but it's a fairly deep change so I wanted to let the dust settle from ML8 first.

It might also be time to serve the TOC as JSON and let the browser render it to HTML. That way the download should be faster, even if the browser then has to do more work. I suspect that would work out better on slow links, and wouldn't make much difference on fast ones.

**Comment by mblakele** [comment]
`Last-Modified` seems to work as expected with Chrome: I see a `304 Not modified` response and no content returned. So the bottleneck is probably local to the browser.

The built-in profiler in Chrome tells me that the vast bulk of the page init time is spent in XHR Ready State Change, initializing the TOC. In my sample this included four fairly large GC events, which could cause stalls or hangs. The profiler points to treeview initialization as a big offender, and it seems to allocate some fairly memory-intensive data structures. Stubbing out treeview init seems to confirm this.

I don't think anything has changed much in that code: more likely it's just that the TOC keeps growing. So rethinking the way the top-level TOC structure loads itself could save quite a bit. We might also be able to replace the treeview code with something more efficient, or optimize its memory usage a bit.

**Comment by mblakele** [comment]
If this change doesn't do the job we can consider replacing treeview with jstree or slickgrid, and also consider the TOC changes outlined above.

**Comment by dsokolsky** [comment]
I think this has caused a problem where it ends up re-initializing the toc on every page load.  Here is how I noticed (while at home on my slow dsl connection):

* Go to a page like this one:
/guide/node-dev/search

* click on the next major heading in the toc (managing transactions)

In most cases this causes the toc initializaion process to happen ("toc loading" displays).

Sometimes I need to click again on something else (in the same toc) to see it.

**Comment by dsokolsky** [comment]
I am using firefox, btw.  I don't see this behavior on the production site, which has the older code.

**Comment by mblakele** [comment]
Is it possible that your cached js is out of date? The most I see in the firefox (36.0.1) console is `updateTocForSelection`, which is as expected. I don't see anything like `toc loading`.

**Comment by dsokolsky** [comment]
It is possible, but I don’t think so.

I first noticed it when paging through a book’s chapters using the next/previous buttons at the bottom of the page.  Some page loads seemed to trigger this.

I will try to nail down a more reproducible case, maybe tomorrow.  

-Danny

**Comment by mblakele** [comment]
How about `/guide/getting-started`? On that path I see a "normal" pjax load when I click on the first link `/guide/getting-started/intro`. But when I click on `Next »` that causes a full reload. Is that the problem?

However I also see that behavior at https://docs.marklogic.com/guide/getting-started — so if it's a bug it isn't newer than the last site push.

**Comment by dsokolsky** [comment]
That is certainly the same behavior I was noticing.  It might be an old problem.  It might also be related to what various people have been talking about wrt slow roc loading.

**Comment by mblakele** [comment]
See if this helps.

**Comment by dsokolsky** [comment]
This is deployed live now.  At least one of our users who was reporting slowness says it is a lot faster now.  I will try and track down some of the others who reported this as well.

**Comment by dsokolsky** [comment]
This is fixed now.
