### ISSUE TITLE
not rendering guide text from a Bulleted paragraph style

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#460]
We seem to have a paragraph style called "Bulleted" in the frame xml, and it is not being converted properly.  An example is in the 4th row of the table in this section:

/guide/app-dev/transactions#id_77307

The text is blank.

It should be treated just like a Body-bullet in the html.

I am not sure exactly when this broke, but I know it was working back in November.  Likely this is fallout from the restructuring.

**Comment by mblakele** [comment]
Yes, looks like a copy-paste bug from when I removed the last of the guide XSLT.

**Comment by dsokolsky** [comment]
That seems to work.  Mike, can you merge this into master please?  I have to update the main site with this (and I guess will need to reload).  Of course, it is currently down, but that is another issue....

**Comment by mblakele** [comment]
Done. Yes, definitely a reload to fix this.

**Comment by dsokolsky** [comment]
This is now fixed in production.  Thanks Mike.
