### ISSUE TITLE
back button should restore version when appropriate

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#461]
Use case: developer is coding on ML8, looks up `json:object-define`. Then developer switches to version 7 to see if `json:object-define` is also available in ML7. Developer then uses the back button to return to the ML8 function page.

Expected behavior: the ML8 page displays with the version selector set to `8.0`.

Unexpected behavior: the ML8 page displays ok, but the version selector remains on `7.0`.

Additional cases: version should also set when returning from 404 page for versions where the function does not exist, such as `5.0`.

**Comment by dsokolsky** [comment]
Yup, I agree, this should work that way.

**Comment by dsokolsky** [comment]
This appear to work well.  And I cherry-picked it over to master as well.
