### ISSUE TITLE
Ordered list breaks unexpectedly in /guide/temporal/temporal-quick-start#id_62247

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#463]
There may be another ordered list bug visible at `/guide/temporal/temporal-quick-start#id_62247`. I see two `1.` items and I think they should be part of the same list. Can you confirm?

If it looks like a code bug, please assign it back to me.

**Comment by dsokolsky** [comment]
Those should be the same ordered list.  But I think this is really a problem with the source, not with the code in the app.  Those paragraphs are Body, and they should be Body-indent.  I think if we made the current code accept Body that it would not work correctly if a Body para showed up after a number, but not within the number.  So we will change the source on this.

**Comment by dsokolsky** [comment]
We fixed the source here, so closing this one.
