### ISSUE TITLE
Intra-module hrefs not working for REST methods

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#466]
Hrefs of the following form for intra-module (but extra-function) jumps for the REST method apidoc no longer work:
```xml
<a href="#ValidateBackup">...</a>
```
Mike suggested making "#verb#name#id" work, which I think would be OK, if "#verb:name#id" isn't practical.

See the ValidateBackup href(s) in management.xml for an example. There are some in RESTclient.xml (#combined-query, #query-options), too, but they're all perverted right now from me trying to work around this bug.

Gory contextual details follow.

When the fixups were done as part of generating the statics, these hrefs worked by finding the anchor id in the module and then just building the rest of the real href from its ancestor apidoc:function.

The only thing that seems to work now that docapp is doing the fixups is a relative link using the full, rewritten path to the containing function. Like this:
```xml
<a href="REST/POST/manage/v2/databases/[id-or-name]#ValidateBackup">
```
A solution that requires a new convention in the source is fine, but preferably not one that requires knowledge of the doc app's rewriting rules.

For XQuery, we use the form `href="#func#id"`, like `#search:search#options"`. Something similar for REST would be OK. Preferably using the method name as it is in the source (with curly braces, pipes, and all the other warts). 

To express links into the REST apidoc from the FM source, we use "verb:name", which is then fixed up by the Awesome Linkerator. Like this: `POST:/manage/v2/database/{id|name}`. Using "#verb:name#id" in the apidoc XML would parallel this nicely. However, it might not be practical since it looks pretty much just like XQuery hrefs of the form "#nsprefix:name#id".

**Comment by kcoleman-marklogic** [comment]
I'm not sure if you have access to the nightlies, but I just checked in a version of RESTclient.xml that uses the format you suggested (#verb#name#anchor) in case you want to have something to play with. I also left one in there of the form #verb:name#anchor for your enjoyment.

POST /v1/alert/match contains an href using the colon-separated form. Anchor id is "combined-query"). It refs back to POST /v1/search.

GET /v1/config/query/(default|{name}) contains an href using the # separated form. Anchor id is "query-options". It refs back to the PUT method of the same name.

**Comment by dsokolsky** [comment]
And Mike, to restate what Kim said earlier, #verb:name#anchor is the preferred way (using a ":" instead of a "#" to separate the verb from the name) to do something, as that matches some other processing we do internally for some links we add to our frame files.  Kim, correct me if I am wrong.

**Comment by kcoleman-marklogic** [comment]
That's correct, Danny.

**Comment by mblakele** [comment]
We don't have many test cases in this area. I just added three, and that should improve as we find problems.

**Comment by kcoleman-marklogic** [comment]
Mike, what format did you settle on? I just tried both #VERB#METHOD and #VERB:METHOD and neither is working.

For example, this in the input XML:
```<a href="#POST:/v1/search#combined-query">``` 

Results in this in being sent to the browser: 
```<a href="./REST/POST/v1/search#combined-query">```

Which resolves to this incorrect URL: ```http://host:port/REST/POST/v1/alert/REST/POST/v1/search#combined-query```

I'm thinking the "." is wreaking havoc and it should just be /REST/....

**Comment by dsokolsky** [comment]
The link Kim is referring to comes from this page:

/REST/POST/v1/alert/match

**Comment by mblakele** [comment]
I think you're right about the `.` — but we can't just remove it or else the link will always go to the default version. This is a drawback to using `/` in URLs when it isn't really meaningful.

I'd rather not rewrite all the links in `page.xsl` for every page display, but that may be the only way.

**Comment by mblakele** [comment]
This is not pretty, but it seems to work with firefox and chrome.

**Comment by kcoleman-marklogic** [comment]
This looks to be working now. Thanks!

**Comment by dsokolsky** [comment]
Mike, can you please merge this one to master?  I am getting an error when I try to do a cherry pick of it (probably due to my git dummyness).

**Comment by mblakele** [comment]
Probably something to do with having to manage two commits. I cherry-picked 99e47bb2ebf3c516425ea66d84b7601db24d6def and 44292937bdc5074835bc84b34c7f4c35a8629787, and then rebased them into a single commit 3515c608ee6c153fdbfe31264239c7f493c8d50c for clarity.

**Comment by kcoleman-marklogic** [comment]
Once more with feeling, I'm afraid. I backported the changes I made for this on b8_0 to b7_0, and the links are resolving back to the default doc version. 

Our friend POST /v1/alert/match in RESTclient.xml contains an href of this form:
```<a href="#POST:/v1/search#combined-query">```

It ends up looking like this in the rendered page. I think there's one hop too many back up the tree.
```<a href="/7.0/../../../../../REST/POST/v1/search#combined-query">```

It winds up resolving to this:
```http://host:port/REST/POST/v1/search#combined-query```

**Comment by mblakele** [comment]
I forgot that `page.xsl` rewrites href values. So we don't need the `../` workaround after all.

**Comment by dsokolsky** [comment]
I updated the code on pubs and reloaded 7.0.  That test case seems to work fwi, and the 8 version still works too.  I'll leave this to Kim to declare it fixed tho.

**Comment by kcoleman-marklogic** [comment]
It looks like it's working. Assuming we don't need to wait on an 8.0 reload, I think you got it this time. Thanks!

**Comment by kcoleman-marklogic** [comment]
I checked 8.0 this morning. Looks good. Leaving this open and reassigning to Danny just because IDK if there's code merging that needs to happen to get it on live eventually - I clearly closed it prematurely last time.

**Comment by dsokolsky** [comment]
Done.
