### ISSUE TITLE
google searches match stuff in the toc 

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#468]
When you do a google search for something like "marklogic REST gzip", you get hits from pages where the only match for gzip comes from the toc.

Maybe we should add some magic to the toc to tell google it is not important.  I am not quite sure how to do this....

I think this is mostly a problem in the docs.

**Comment by sammefford** [comment]
My first guess is we load the toc as JSON via javascript to keep it out of search results.  But I'm sure google has guides on how to do this right.

**Comment by mblakele** [comment]
It's already an ajax request, so google is indexing via a simulated browser. We could try a couple of things. Adding `<meta name="robots" content="noindex">` to the TOC html might work, but since it's ajax I'm not sure. Another solution might be `robots.txt`: add a disallow directive for everything under `/media/apiTOC/`.

**Comment by dsokolsky** [comment]
I like the robots.txt notion.  We do have a robots.txt file, it would be easy to try it out.

https://github.com/marklogic/RunDMC/blob/master/src/robots.txt

**Comment by dsokolsky** [comment]
Another thought...if we go the robots.txt route, maybe we should just disallow all of ``/media/`` ?

**Comment by mblakele** [comment]
I think we should be conservative and only block the TOC: `Disallow: /media/apiTOC/`. I've heard google does some OCR of images, so blocking the guide images in `/media/` might be counterproductive.

**Comment by dsokolsky** [comment]
I cherry-picked this into master, and pushed it live.  We will see if it makes any difference after a while.

**Comment by mblakele** [comment]
Right now https://www.google.com/search?q=marklogic+REST+gzip is showing me "about 4310 results".

If you want a faster test cycle I think the google webmaster tools let you request a recrawl.

**Comment by dsokolsky** [comment]
I just told it to crawl, so we can take a look tomorrow and see how it looks.

**Comment by dmcassel** [comment]
@dsokolsky I think this is fixed, can you confirm and close?

**Comment by dsokolsky** [comment]
Yes, this is fixed.
