### ISSUE TITLE
search is not highlighting the api name if it is a match

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#470]
If you search for /v1/search or something that matches an api name, highlight does not highlight the api.  This sounds vaguely familiar like we decided not to do it or it was hard or something, but I am not sure.

At any rate, it would be nice if it did highlight the match in the api title.  To repro:

1) search for /v1/search
2) click on a REST api link (for example, GET /v1/search)

It will go to the page but not highlight the first match (the title).  If there are other matches on the page, it will scroll to the first match.

**Comment by mblakele** [comment]
It's similar to `xsl:template match="api:function"` from #368. The main `page.xsl` does highlighting for all content, but `apidoc/page.xsl` overrides it in a few places and so those don't get highlighted without extra work.

**Comment by dsokolsky** [comment]
Looks good.  I pushed it to master too so next time we update the live site this will be fixed.
