### ISSUE TITLE
Account formatting is messed up

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#473]
Login, Sign In, and the button with your name on it all have bad formatting on docs.marklogic.com. The formatting for these areas was changed on developer, but it looks like it didn't get across to the docs site. 

@jimkrill, can you fix this along with your other work in progress? (tagging @stephen-gehring-ml, too)

**Comment by kcoleman-marklogic** [comment]
The button with your name on it is bad even on developer.marklogic.com, though the login dialog looks OK. This is the menu you get when you click on your name, with "Edit Profile" and "Logout" choices.

**Comment by dmcassel** [comment]
- developer: when logged in, click on your name. The dropdown menu is transparent (although it does work)
- docs: I don't think bootstrap is getting loaded on the docs site yet (same codebase, but different template). The classes are set, but with no bootstrap, we just have a plain button
