### ISSUE TITLE
Add state to community signup form

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#474]
Marketing needs to capture the state.

**Comment by seongbae-ml** [comment]
Hi Dave,

Can you please remind me if you're using abbreviated or full state name when you submit the form?

Thank you.

**Comment by dmcassel** [comment]
@seongbae-ml, looks like it's the full state name, as in "Pennsylvania"

**Comment by seongbae-ml** [comment]
Can we make it abbreviated? PA, VA, etc.  Both Marketo and Salesforce expect abbreviated state names.  If not, the state informatio won't be captured.

Let me know if I should create a separate ticket for that.

**Comment by dmcassel** [comment]
To be precise, the abbreviations should be uppercase: "PA", correct?

**Comment by dmcassel** [comment]
Confirmed offline that abbreviations are to be upper case.

**Comment by dmcassel** [comment]
Pushed to prod. @seongbae-ml, you should start seeing two-letter codes for states now. Please verify.

**Comment by seongbae-ml** [comment]
Thank you. I see two letter codes now.
![screen shot 2015-06-22 at 12 15 44 pm](https://cloud.githubusercontent.com/assets/9138931/8286601/7e1142e2-18d8-11e5-81d9-84342d6b3a52.png)
