### ISSUE TITLE
Verify the Search API 5-minute guide

### ISSUE THREAD

**Issue by jmakeig** [marklogic/RunDMC#475]
Revisit the [“5-minute Guide to the Search API”](https://developer.marklogic.com/learn/2009-07-search-api-walkthrough) to make sure the examples still work _and_ they represent current best practices.

**Comment by jmakeig** [comment]
There are likely a whole bunch of other tutorials that could use this kind of love as well.

**Comment by dmcassel** [comment]
@jmakeig, I'm sure there are. Please file if you encounter things that clearly need help.

**Comment by dmcassel** [comment]
@jmakeig, I made some updates to this tutorial today. I focused more on make-it-work than best-practices, but I think for someone using the Search API directly (instead of the REST API) it's good. Please review if you can. I'll close this one if I don't hear from you in a few days.
