### ISSUE TITLE
Possible bugs with content in docs: "Javascript getting started"

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#486]
I started to run through the example on this tutorial on the docs site…
https://docs.marklogic.com/guide/getting-started/javascript

When I try step 4 “Enter var obj = {key1:"value1", key2:"value2”}; obj;”  into query console.  
I get a internal server error…

![screen shot 2015-05-12 at 6 58 27 am](https://cloud.githubusercontent.com/assets/4975480/7589336/eb46a708-f876-11e4-9f14-46c65b52ba52.png)

I am running on ML 8.0-20141124

I hope this helps!

**Comment by dsokolsky** [comment]
Stephen, please install 8.0-2.  You are using an old ea build.

**Comment by stephen-gehring-ml** [comment]
Hi Dan,
You may want to consider footnoting that in the tutorial so the user does not give up and has clear path to troubleshoot the issue.

Hope this helps!

**Comment by sgehringDesign** [comment]
Hi @dsokolsky  & @dmcassel 
I upgraded based on what is available on the developer ... see below...

![screen shot 2015-05-15 at 1 28 29 am](https://cloud.githubusercontent.com/assets/254283/7649486/4e64932c-faa2-11e4-8d7a-34e6ec782724.png)

Then I tried the tutorial again and I still get the same error on step 4.
![screen shot 2015-05-15 at 1 31 35 am](https://cloud.githubusercontent.com/assets/254283/7649495/67eb516e-faa2-11e4-8bfb-e5b9cc1c7733.png)

**Comment by dmcassel** [comment]
Looks like your attempt to upgrade didn't work, because the installed thought your nightly build is newer. I'll send you an internal link on how to full remove the nightly.
