### ISSUE TITLE
Formatting on SQL to ML mapping page

### ISSUE THREAD

**Issue by heymattallen** [marklogic/RunDMC#487]
The formatting on this page is wonky: http://developer.marklogic.com/learn/sql-marklogic-mapping

It's great content, so worth putting it through another iteration to clean up the formatting and make the comparison really clear.

**Comment by dmcassel** [comment]
Wow, yeah, rather broken. Thanks for pointing it out. 

I've also thought it would be good to add JS or REST equivalent searches, too.

**Comment by dmcassel** [comment]
Fixed the formatting.
