### ISSUE TITLE
Display new and updated content

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#489]
Create a tag that lists the most recently added or updated content on DMC. The tag must be something I can use on the home page. See src/view/tag-library.xsl for examples. 

- Recently updated should be based on the "last-modified" property in the property fragment. 
- Formatting should use Bootstrap classes
- The number of items displayed should be configurable

**Comment by dsokolsky** [comment]
I would be hesitant to use the last-modified property for that.  Then it will show stuff when you do a minor update (like fix a word or link).  Instead, I think it would be better to keep a field in the tag somewhere, or in a place on the page.  Just my opinion though....

**Comment by dmcassel** [comment]
Valid point. I was thinking minor updates are a bit less common than new blog posts, tutorials, or other pages, and as such it wouldn't be a big deal. Worth thinking about.

**Comment by dmcassel** [comment]
Revised approach: limit to blog posts, tutorials, and community projects (identifiable by collection). Use the ml:last-updated element. I'll need to do some data cleaning on that element for tutorials and maybe projects. Tutorials populate that element manually through the form, so we have a variety of values in there now. 

- make sure last-updated is always populated
- make sure last-updated has a valid xs:dateTime
  - this means changing the form to require type validation for tutorials
  - when displaying tutorials, convert xs:dateTime to a human-readable date (like "Oct 22, 2015")

I've asked @stephen-gehring-ml for UI ideas. Planning to display 3-5 of the most recent new or updated content links.
