### ISSUE TITLE
Change the purple bar to match www

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#491]
Can we change the purple bar on the "www" site to match MarkLogic.com.
http://www.marklogic.com

The PMG developer team has created a bower component for it here:
https://github.com/marklogic-marketing/ml-marketing-module-purple-menu-bar

**Comment by dmcassel** [comment]
@stephen-gehring-ml, I got a 404 on that other repo.

**Comment by sgehringDesign** [comment]
@seongbae 
Can we give Dave access to the marketing repo? 
Or make the purple bar a public repo?

**Comment by seongbae-ml** [comment]
@stephen-gehring-ml Sure. I just sent Dave invitation.  

@dmcassel Let me know if you still can't access it.

**Comment by dmcassel** [comment]
@seongbae-ml I'm in now, thanks

**Comment by seongbae-ml** [comment]
@dmcassel By the way, Dave, I've made that project public. So anyone should access to it.

@stephen-gehring-ml

**Comment by dmcassel** [comment]
@seongbae-ml it looks to me like the only interactive part is language selection, which is not yet available for DMC. Correct?

**Comment by seongbae-ml** [comment]
@dmcassel Right.  You can hide/remove that if you need to.  Also, if you feel that the links on the right side are not relevant for the Community website, please feel free to remove them as well.  MLU folks asked similar question about those links on the right side.  What we'd like to see is left side links stay consistent.

**Comment by dmcassel** [comment]
Done and deployed. I changed the right side to just have an "Ask a Question" link. 

@dsokolsky, at some point we should do this for docs. The main thing would be to include Bootstrap on the docs page to get those classes; don't want to do that without your involvement.

**Comment by seongbae-ml** [comment]
@dmcassel  Thank you, Dave!
