### ISSUE TITLE
The  Note icon is not showing up in Firefox browser on pubs.marklogic.com

### ISSUE THREAD

**Issue by jmckean17** [marklogic/RunDMC#496]
Icon looks like it has bit-rot in IE and Chrome on pubs.marklogic.com (http://pubs.marklogic.com:8011/guide/semantics/loading). Icon looks fine on docs.marklogic.com. (http://docs.marklogic.com/guide/semantics/loading)

**Comment by dsokolsky** [comment]
I can reproduce this now.  It seems like it is not putting the href in there.  Not sure why at this point.  Here is the html for that snippet:

``<p class="note"><a id="id_pgfId-1097936"></a>The embedded triples must be in the MarkLogic XML format defined in the schema for <a href="/sem:triple">sem:triple</a><code> </code>(<code>semantics.xsd</code>). </p>``

Notice no href.  Odd.

**Comment by dsokolsky** [comment]
OK, the reason it does not have an href is because screen.css controls this.  It does not seem like anything changed, and it still works fine in production.  

Here is the code that does this:

**Comment by dsokolsky** [comment]
https://github.com/marklogic/RunDMC/blob/master/src/css/screen.css

line 2646.   

@dmcassel can you think of anything that would make this stop working?

**Comment by dmcassel** [comment]
It's not the CSS, it's the image itself. See http://pubs.marklogic.com:8011/images/ml_icons_note.png. Looks like that file got messed up somehow. I'd reload it in the pubs database.

**Comment by dsokolsky** [comment]
Thanks Dave, that was the hint I needed (I had noticed it myself but was unable to put 2 and 2 together....).  I believe that icon is not actually in the database, it is served up from the filesystem.  But somehow it got corrupted.  I deleted it and then did a git reset on that machine and that seems to have fixed it.  Thanks Jane, thanks Dave.  Reopen this if you see it again.
