### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#498]
Blog posts look pretty terrible on a mobile device. Bootstrap is already being used; update CSS to make it work better.

**Comment by dsokolsky** [comment]
You might want to look at what @mblakele did for the docs side.  The docs look pretty decent on mobile devices.

**Comment by dmcassel** [comment]
Cool, thanks @dsokolsky

**Comment by dmcassel** [comment]
content on DMC and the header for both DMC and docs have been greatly improved.
