### ISSUE TITLE
Slow search/filtering on docs site.

### ISSUE THREAD

**Issue by bradmann** [marklogic/RunDMC#509]
When searching the MarkLogic API docs (http://docs.marklogic.com), the result filtering is very slow. Because this is a live search, it is very frustrating to use. Please speed this up.

**Comment by dsokolsky** [comment]
The search box is the box on the upper right of the page.  It should be fast.

The box above the toc is a filter box to filter the TOC.  It is not so fast (although it is all client side javascript).  It does have an wierd feature that if you hit return it will run a search, though...

But yes, the filter box could use some work to be better.

**Comment by paxtonhare** [comment]
I have some code to speed up the toc filter. This is what @bradmann  is referencing.

**Comment by dsokolsky** [comment]
Does that mean you are going to take this Paxton?  That would be great if so.

Let me know though, as I have a bunch of code on the docapp branch that I am going to need to merge into master probably this week.  It might make sense for you to do the work on the docapp branch if you plan on doing it soon.

**Comment by paxtonhare** [comment]
I'll take it. And I'll look at the docapp branch.

**Comment by paxtonhare** [comment]
This is live now. Closing it.
