### ISSUE TITLE
http://docs.marklogic.com/xdmp:eval css is messed up

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#523]
It looks like the addition of bootstrap caused an issue here (look at the list under $options in the args description):

http://docs.marklogic.com/xdmp:eval

I have to make some more overrides in screen.css to cover this.

**Comment by dmcassel** [comment]
I think the main problem is the font-size on blockquote. I think this will fix it:

    #page_content .parameters blockquote { font-size: initial; }

**Comment by dsokolsky** [comment]
Thanks Dave.  That did not work though.  Not sure why...

**Comment by jenbreese** [comment]
Try #page_content .parameters blockquote { font-size: inherit; } instead.

**Comment by dmcassel** [comment]
@dsokolsky has this been deployed?

**Comment by dsokolsky** [comment]
Yes, this is deployed.
