### ISSUE TITLE
comments are not available on pages that do not already have comments

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#543]
I am not sure when this started, but comments have disappeared from pages that do not already have comments.  Here is an example:

http://docs.marklogic.com/xdmp:external-security

For pages that do have comments, they are there:

http://docs.marklogic.com/xdmp:eval

@paxtonhare and @dmcassel , can you think of anything that might have recently caused this?  Like I say, I don't know when this happened.

**Comment by dmcassel** [comment]
@dsokolsky I see the comment section on http://docs.marklogic.com/xdmp:external-security. Mac 10.10.5, Chrome 47. Works in Firefox, too.

**Comment by dsokolsky** [comment]
Interesting.  I thought it was not working yesterday.  Probably just a mental problem on my side.

**Comment by kcoleman-marklogic** [comment]
It is not a mental problem. The struggle is real! I think it is the squirrely TOC nav pane interactions.

I do not see the commenting widgets on the funciton pages, either, unless I do one of the following:
* Go directly to the function URL, like the link to xdmp:external-security that's in this bug.
* Reload the page after navigating to it via the left nav panel.

If you navigate to a function via the TOC, no joy w/o reload. Worse, it appears necessary to do the reload on each and every function page, every time, which seems...unfortunate.

**Comment by dmcassel** [comment]
Okay, I see it now. Problem occurs even when you go from one function page (seeing comments) to another function page via the TOC -- no comments. Don't know what might have caused that or how long it's been happening.

**Comment by paxtonhare** [comment]
I have a fix for this. Just need to check it in and whatnot.
