### ISSUE TITLE
h5 text gets no styling

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#553]
The FrameMaker paragraph style "Heading 4" becomes an h5 when rendered as HTML. The CSS adds no styling at all for h5, AFAICT. You can't even tell the headings are links unless you happend to mouse over them. Such subsecs are difficult to distinguish from nearby body text. It would nice if h5 had some kind of styling, even if it was just underline or bold.

Here are a couple examples:

http://docs.marklogic.com/guide/semantics/inferencing#id_90792
http://docs.marklogic.com/guide/rest-dev/documents#id_88350

And here's an example of the underlying HTML: 
```html
<h5><a href="#id_90792" class="sectionLink">Using Rulesets</a></h5>
```

**Comment by dsokolsky** [comment]
See how that looks (I pushed it to pubs).

**Comment by dmcassel** [comment]
Another option to consider -- we have Bootstrap available; if other formatting were cleared out and Bootstrap formatting allowed to go through, it would probably look better.

**Comment by kcoleman-marklogic** [comment]
That's definitely a significant improvement. Thanks, Danny. 

I wish H5s stood out a bit more, but I think doing so would make them too hard to distinguish from the H4's. The differentiation between our heading levels is pretty subtle, all around, so there's not much wiggle room.

Danny, do you want to take this back til you push to DMC, or want me to close it?

I'm wallowing in ignorance wrt Bootstrap, so I have no opinions on that head, even if one was solicited. :)

**Comment by dsokolsky** [comment]
I'll take it back.

I don't think it is worthwhile right now to completely use bootstrap here for two reasons: 1) it will be a lot of work and quite risky in terms of getting things wrong (we broke a whole bunch of stuff when we added bootstrap to the project, for example) 2) the pages in the doc are very different from the pages on dmc, so it is likely that things would look strange.

**Comment by dsokolsky** [comment]
Looks like I still need to merge this into master.

**Comment by dsokolsky** [comment]
I merged this into master and pushed it live.  Seems to work, so closing this.
