### ISSUE TITLE
Node & ML Instruction Suggestion 

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/RunDMC#565]
Hi Dave & Danny,

For this tutorial: https://developer.marklogic.com/products/node

you may want to specifiy that the user should run "node init" before running... "npm install marklogic --save"

Your audience maybe still beginners... =O)

Steve

**Comment by dmcassel** [comment]
The reader is already instructed to run `node init` in step 2 under "System requirements and installation".
