### ISSUE TITLE
Header overlap

### ISSUE THREAD

**Issue by jmakeig** [marklogic/RunDMC#574]
[<img width="612" alt="issue" src="https://cloud.githubusercontent.com/assets/176233/17310003/9bf287a4-57f6-11e6-80c2-598177697202.png">](http://developer.marklogic.com/adventure/developer/java/start)

**Comment by jmakeig** [comment]
Safari 9.1.1 on OS X 10.11.5 (15F34)

**Comment by dmcassel** [comment]
Safari 10.0.1, OS X 10.10.5 doesn't show this. Maybe this was a safari problem? 

@jmakeig have you upgraded Safari, and if so, do you still see this?

**Comment by jmakeig** [comment]
Nope.
