### ISSUE TITLE
Interrupted numbered list incorrect

### ISSUE THREAD

**Issue by jmckean17** [marklogic/RunDMC#578]
I have a couple of instances of incorrect numbered lists in the online docs when they are interrupted by a screenshot. This is in my encryption chapter (part of the Admin guide).
Here’s one:
http://pubs.marklogic.com:8011/9.0/guide/admin/encryption#id_61056
When the numbered list starts up again after the screenshot, it starts back at 1, instead of 4.

This second instance is more fun. After the screenshot, the list is supposed to be alphabetical (a., b. c) , but switches to numbered list starting with 1.
http://pubs.marklogic.com:8011/9.0/guide/admin/encryption#id_pgfId-1070758
And then, when the real numbered list commences again, it’s been transformed into an alphabetical list instead of numbered one.

All of these things are correct in the PDF, it is only the online HTML that is cattywampus.

**Comment by dsokolsky** [comment]
You can usually fix this in the Frame source by changing the paragraph styles of the paras between the numbers.  Look at another instance that contains images between the numbers but converts properly.

**Comment by gfurbush** [comment]
It's not a Frame issue.  It's a run DMC issue.

**Comment by jmckean17** [comment]
Looking at this section, where things seem to work: http://pubs.marklogic.com:8011/9.0/guide/admin/webdav#id_21458
Looks like body tag breaks the list, where body indent tag does not. After I confirm with tonight's build, I'll close the bug. :-)   (hi Danny!)

**Comment by dmcassel** [comment]
@jmckean17 looking at the examples on pubs, this appears to have been dealt with. Can we close this one?

**Comment by jmckean17** [comment]
Yes @dmcassel this is fixed now. Closing this bug. Thanks!
