### ISSUE TITLE
Inserting elements from schema files into the API docs

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#584]
The documentation tools that extract elements from the schema files and inserts them into our API docs requires that the element be of type xs:complexType.  However, I frequently encounter situations in which the to-be-documented element is a simple xs:element type.  Is there anything we can do to capture these as well?

Now it may be that we don’t want to capture all simple elements, so could we add an attribute, such as ‘doc=”true”’?

Copied from bugtrack: 41501

**Comment by kcoleman-marklogic** [comment]
Sorry, Dave, Gordon already created a GitHub issue (#577) for this. I don't know how I missed it. I'm going to close this one and put the Oct. milestone label on the previously existing issue. Mea culpa.
