### ISSUE TITLE
Setup is corrupting some links

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#587]
From @gfurbush: 

In /9.0/REST/POST/manage/v2/databases/[id-or-name]#AddFR
 
The Configuring Database Replication link should go to:
 
/9.0/guide/database-replication/configuring#id_52262

**Comment by dmcassel** [comment]
From @kcoleman-marklogic:

Here's probably what's wrong.
 
In setup.xqm, there is the following function:
 
    declare function stp:fix-guide-names(
      $version as xs:string,
      $href as xs:string,
      $guides as element(apidoc:guide)*)
    as xs:string
    {
      if (empty($guides)) then $href
      else stp:fix-guide-names(
        $version,
        replace($href, $guides[1]/@source-name, $guides[1]/@url-name),
        subsequence($guides, 2))
    };
 
That `fn:replace` call that I've highlighted is too naive. It makes the rash assumption that no guide's source name will ever be a subset of another. Since we have a "database-replication" and a "replication" guide, Bad Things happen.
 
For example.
 
    let $url-name := "flexrep"
    let $source-name := "replication"
    let $href := '#display.xqy?fname=http://pubs/6.0doc/xml/database-replication/configuring.xml%2352262'
    return fn:replace($href, $source-name, $url-name)

=>
 
    #display.xqy?fname=http://pubs/6.0doc/xml/database-flexrep/configuring.xml%2352262
 
I drew that input from this entry in document-list.xml + the raw input from management.xml in the zip file.
 
    <guide url-name="flexrep" source-name="replication">
        Provides step-by-step information on replicating MarkLogic Server
        content using Flexible Replication.</guide>
 
That code is just too damn dumb. Perhaps one or more of the fn:replace flags will help, but I'm dubious. I think it more likely that it has to be smarter about exactly matching an entire path step. I don't know is if the guide name is reliably demarcated by '/'s in all the places this function might get used.

**Comment by kcoleman-marklogic** [comment]
I backed out the local merge of #571 on pubs (for hygienic reasons), pulled this change in, and reloaded the docs. Gordon reports his problematic link is working, and I spot checked several other links from the apidoc to the guides and vice versa, as well as links between guides. AFAICT, this is working like a champ.

**Comment by dmcassel** [comment]
Okay. I'll merge into master and deploy that change.
