### ISSUE TITLE
doc version dropdown is too narrow to show complete version info

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#589]
Something on DMC causes the version selector dropdown on docs.marklogic.com to be too narrow to display the full version text in Chrome. Firefox does not seem to have the same problem, from what Gordon tells me.

If you navigate to docs.marklogic.com in Chrome, you should see that the version drop in the upper left (below the company logo) displays "MarkLogic" instead of "MarkLogic 8". If you look at the same thing on pubs, you can see the full version.

When I diff'd the docapp branch against master, I didn't spot anything that would explain this, and I just merged master into docapp last week, so it shouldn't be missing anything that matters. However, Chrome dev tools indicate there's css entry that's not being applied on live, from apidoc.css: https://github.com/marklogic/RunDMC/blob/master/src/css/apidoc.css#L124. IDK that that's the source of trouble, but at least it is a place to start looking. 

Because it makes it impossible to tell at a glance what version you're looking at, I'm marking this as a priority issue.

**Comment by dmcassel** [comment]
I'm unable to reproduce this in Chrome (or Firefox or Safari, just for fun).

**Comment by kcoleman-marklogic** [comment]
How peculiar. I guess it's just a personal problem then, and I shall cease to worry my pretty little head over it. Just for the record, here is what I see:
![dmc_ver](https://cloud.githubusercontent.com/assets/1951367/18838598/de952a66-83bc-11e6-948a-e3751dcd5dcd.gif)

**Comment by dmcassel** [comment]
I'm seeing this now. Not sure why.

**Comment by kcoleman-marklogic** [comment]
It doesn't happen on pubs or docs-ea (which is based off the same branch as pubs). FWIW, pubs is running the docapp branch. I failed to have an epiphany when I looked at the diffs, but I don't really know which rocks to look under, either.

**Comment by dmcassel** [comment]
fixed

**Comment by kcoleman-marklogic** [comment]
How odd. The font weight is heavy on pubs. It's just that the selection box is wider. However, I'm not going to look the gift horse in the mouth. Thank you very much, Dave.
