### ISSUE TITLE
Need to generate XQuery API doc for optic API

### ISSUE THREAD

**Issue by gfurbush** [marklogic/RunDMC#592]
I have documented a JavaScript version of the "optic" API in the file /docs/modules/optic.xml.

This is a unique API in that its organized as "prototyped objects," which required a lot of contortions to get the doc build and RunDMC to generate the correctly organized API doc.  You can see what I've talking about under "Optic" in the JavaScript Library Modules on pubs.

Now I'm tasked with documenting the XQuery version of the optic API.  I was hoping that I could do something similar to the alert.xml or spell.xml doc module files, which successfully generate both XQuery and JavaScript using the 'class=' attribute.  However, I've discovered the way optic.xml was originally created for the prototype functions doesn't allow for a single XQuery namespace.

For example, I can't mix the 'object' and 'lib' attributes in the apidoc:method element without getting a result like, opPreparePlan, when I want op:functionname for XQuery and PreparePlan.methodname for JavaScript.  

I also can't create separate apidoc:function class="xquery.... and apidoc:method class="javascript..... elements without breaking XML rules.

I also can't figure out how to get the optic API to show up under XQuery Library Modules.

I understand that this my be hard for you to get your head around these problems (lord knows, it's been a long journey for me), so it might be better if we were to meet to discuss the problems and the potential solutions.

**Comment by gfurbush** [comment]
I think I may be homing in on a solution, but I need some help.

In RunDMC/src/apidoc/setup/setup.xqm there's a stp:copy-content-from-method, as shown below.  What this does is grabs the content from a method description and wraps it in a new name.  For example, the following will take the contents of the "ModifyPlan.prototype.where" method and wrap it in a new name, "AccessPlan.prototype.where".

  <apidoc:method name="prototype.where" object="AccessPlan" 
	  bucket="XQuery Library Modules"
	  category="Optic" subcategory="AccessPlan Object" 
          copy-content-from="ModifyPlan.prototype.where">
  </apidoc:method>

So what I've done for XQuery is the following:
  <apidoc:function name="where" lib="op" 
	  bucket="XQuery Library Modules"
	  category="Optic" 
          copy-content-from="ModifyPlan.prototype.where">
  </apidoc:function>

Notice I'm using 'function' with 'lib' because these are the keys to getting something to show up in under the XQuery API docs.   What I end up with is an "Optic (op:)" category and a list of function names in the navigation pain.  So far so good.  However, when I open up the function page, I simply see:

## op:where
        op:where() as 

I suspect this is because I'm trying to grab a 'method' element and wrap it in a 'function' element.
What I need is for such an operation to work correctly.

declare function stp:copy-content-from-method($nodes as node()*) as node()*
{
for $n in $nodes return
typeswitch ($n)
  case document-node() return
      document{stp:copy-content-from-method($n/node())}
  case text() return $n
  case binary() return $n
  case comment() return $n
  case processing-instruction() return $n
  case element (apidoc:method) return
      if (exists($n/@copy-content-from))
      then let $s := tokenize($n/@copy-content-from/string(), "\.")
          (: the name can have dots in it :)
           let $object := $s[1]
           let $name :=
               string-join($s[2 to last()], ".")
           return
           element apidoc:method {$n/@*,
               $n/../apidoc:method[@name eq $name][@object eq $object]/node()}
      else $n
  default return
      if ($n instance of element() ) then
        element {name($n)} {$n/@*, stp:copy-content-from-method($n/node())}
      else $n
};

**Comment by gfurbush** [comment]
Kim created another case statement for api:function and it works on her test server.

We need to push this change to pubs, and then later, to docs.

There is one remaining issue, however:  Because of the unique nature of the optic API, the automatic cross references between the JavaScript and XQuery functions are broken (see the upper right-hand link on each page).   These need to be fixed.

**Comment by kcoleman-marklogic** [comment]
OK, I've committed that change to docapp, so it'll affect pubs after the next build (or reload). That other local repo we're working out of is a mess, so this is a good way to make sure there are no other changes you need from there, @gfurbush. 

I don't think this work belongs on master for now. It's quite specific to ML9 and very experimental.
