### ISSUE TITLE
Test docs bootstrap

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#594]
@kcoleman-marklogic reports that after bootstrapping just docs, there was a forest missing that had to be created manually.

**Comment by kcoleman-marklogic** [comment]
The command I ran was: `./ml local bootstrap docs`, and the error I got in the log was the following:
```
XDMP-NOSUCHFOREST: xdmp:forest("RunDMC-api-rawdocs-001-1") -- No such forest RunDMC-api-rawdocs-001-1
```
(I can't recall what the related command line error was now, but it was of the "I've fallen and can't get up" variety. :) )

I worked around the failure by manually creating the forest and rerunning the bootstrap.
