### ISSUE TITLE
mlcp download page does not point to the current documentation

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#598]
Very minor content quibble on DMC. On this page:

http://developer.marklogic.com/products/mlcp

The link to the documentation near the bottom of the page should point here:

http://docs.marklogic.com/guide/mlcp

And the link text should be "The mlcp User Guide".

The link currently on the download page still works, so this is not a big deal. However, the documentation was moved into its own guide about a year ago, so that link is just a stub topic now. Would be better to link directly to the guide.

**Comment by dmcassel** [comment]
fixed
