### ISSUE TITLE
ERROR: 404 "Not Found" when deploying modules

### ISSUE THREAD

**Issue by seongbae** [marklogic/RunDMC#601]
Hi,

When I run "ml local deploy modules", I get following error:

```
MacPro-2352:rundmc sbae$ ./ml local deploy modules
Skipping deployment of src to filesystem..
Loading REST properties in /Users/sbae/Projects/rundmc/rest-api/config/properties.xml
ERROR: 404 "Not Found"
ERROR: 
```

This used to work before when we deployed the MarkLogic Search wordpress plugin but it seems like something's changed after that.  I am using MarkLogic 8.0-5.2.  The only change I made in local.properties is changing port numbers and adding following line:

server-version=8

Any ideas why I'd get 404?

**Comment by dmcassel** [comment]
The default settings use the filesystem, which is appropriate for most of the application but not the REST API server. Change app-modules-db to ${app-name}-modules and modules-root to / in your local.properties file. Be aware you will probably need to delete a couple soft link files that will be pointing to nothing. See #441. 

Longer term, I should change the build.properties file to match those settings and override locally.

**Comment by seongbae** [comment]
Thanks, @dmcassel.  Looks like some progress made.. but REST app is not fully configured it seems like.  I get following messages:

```
MacPro-2352:rundmc sbae$ ./ml local deploy modules

Loaded 1383 documents from /Users/sbae/Projects/rundmc/src to localhost:8013/RunDMC-modules at 10/14/2016 10:31:52 am

Loading REST properties in /Users/sbae/Projects/rundmc/rest-api/config/properties.xml
ERROR: 404 "Not Found"
ERROR: 
MacPro-2352:rundmc sbae$ 
```

And when I go to localhost:8020 in my browse (rest port), I see blank screen.

<img width="1031" alt="screen shot 2016-10-14 at 10 34 20 am" src="https://cloud.githubusercontent.com/assets/1762739/19391260/ce9aa938-91f9-11e6-82ad-22d25f596e44.png">

Here is what I have in local.properties:
```
server-version=8
app-modules-db=${app-name}-modules
modules-root=/
```

**Comment by dmcassel** [comment]
@seongbae the problem turned out to be a ML7 versus ML8 difference. Add this to your local.properties:

    rest-rewriter=/MarkLogic/rest-api/rewriter.xml

**Comment by seongbae** [comment]
@dmcassel Sweet! It worked!  Thank you Dave.
