### ISSUE TITLE
extra leading whitespace on docs section dropdown

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#632]
![whitespace](https://cloud.githubusercontent.com/assets/1951367/20801552/2dce3540-b79e-11e6-8826-6ec778cb183c.gif)

I see this in both Firefox and Chrome. It's happening on the staging host, but not on live, so it's some change that has crept in since the last push to live.

The dropdown box has also become squished right up against the "Section:" label, but that doesn't look nearly as dorky as the leading whitespace. :)

**Comment by dmcassel** [comment]
I see this in FF not Chrome, but that's enough to work on it.

**Comment by kcoleman-marklogic** [comment]
This is your punishment for making me touch IE:

![whitespace2](https://cloud.githubusercontent.com/assets/1951367/20802619/735d5b38-b7a1-11e6-8d80-18339a47909a.gif)

(In case it isn't clear from my smart-ass comment, in IE there's trailing whitespace as well as leading. :) I don't see it on live.)

**Comment by dmcassel** [comment]
Me and my big mouth. :)

**Comment by kcoleman-marklogic** [comment]
This is working properly now on stage.
