### ISSUE TITLE
doc nav panel missing scrollbar on stage

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#633]
Our dearly beloved TOC nav panel on the left side of the docs pages no longer has a scrollbar on the staging host. I see this on Chrome, IE, and FF.

**Comment by dmcassel** [comment]
good catch, likely related to #343.

**Comment by kcoleman-marklogic** [comment]
This is working properly now on stage.

**Comment by dmcassel** [comment]
fixed
