### ISSUE TITLE
Search suggestions feature is broken

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#640]
When you type in the search box, you're supposed to get a list of suggestions as you're typing. During the rewrite of the header to make it mobile friendly, I removed a class that's needed to find the search box. When I put that class back, the suggestions appear, but not in the right place.

**Comment by dmcassel** [comment]
I've got the UI fixed, but I'm seeing a problem on stage and production with the suggestion responses. On localhost, when I hit `/service/suggest?pos=4&substr=admi&version=9.0`, I get back:

    ["admin", "admin:appserver-add-module-location", "admin:appserver-add-namespace", "admin:appserver-add-request-blackout", "admin:appserver-add-schema"]

On stage and prod, I get back 

    ["admin", "admin-alreadyreplica", "admin-attachshareddiskfailover", "admin-badcerttemplate", "admin-badcustomfield"]

I only have v9 docs loaded on localhost, while stage and prod have v8. It's possible that's the problem, but a difference in configuration seems more likely.

**Comment by kcoleman-marklogic** [comment]
FWIW, I see the same thing on pubs that you see on your localhost with "admi", and we have all doc versions loaded over there.

**Comment by dmcassel** [comment]
Good to know. This is definitely a separate problem than the UI being turned off, but I figure it's worth a look to see whether it's a quick fix. If not, I'll file a separate bug.

**Comment by dmcassel** [comment]
Looks like this isn't actually a problem; rather, it's a difference in the loaded data. The examples I saw on stage and prod are correct -- they are error codes.

**Comment by kcoleman-marklogic** [comment]
Yes, they are valid suggestions. Sorry, I didn't realize that was the concern.

However, they're around on pubs (and your localhost) as well as on stage, so I'm still left wondering why the suggestions are so different. Not a big deal. I just think it's a bit weird. 

It's all in the index being used as the suggestion source, just the weighting or something is apparently different. (IDK how `search:suggest` varies from `cts:element-values` with a start pos.) In general, there seem to be some oddities about the suggestions, but they're not relevant to this bug.

**Comment by dmcassel** [comment]
fixed & deployed
