### ISSUE TITLE
RunDMC Spazing out on Firefox

### ISSUE THREAD

**Issue by gfurbush** [marklogic/RunDMC#657]
I can't view the 'Section' pull-down menu for the docs in runDMC using Firefox (see attached image).  I've tried restarting Firefox and even rebooting my laptop.  No joy.

It works in Chrome, however.

![image](https://cloud.githubusercontent.com/assets/2280725/22667163/773f291c-ec70-11e6-9d9a-dae1e673a7f7.png)

**Comment by dmcassel** [comment]
I can't reproduce this on either docs-ea or the live docs site. Anybody else?

**Comment by kcoleman-marklogic** [comment]
FWIW, it's not doing anything wrong for me. I made sure I updated FF (since I don't usually use it). I tried it both before and after clearing my cache, and with and without logging in to DMC.

**Comment by gfurbush** [comment]
I had the problem all day yesterday.  Today, everything is fine.

I don't understand how it "got fixed."

**Comment by dmcassel** [comment]
From the screenshot you posted, it looks like out-of-date CSS to me. Since it's not reproducible and has cleared up for you, I'm going to close this one, but please re-open if you continue to see it.

**Comment by gfurbush** [comment]
Fine to close.  But can you explain the circumstances in which the CSS would get out of date and how I would fix the problem?

**Comment by dmcassel** [comment]
It looks like what I saw with CSS from before the implementation of the Save Preference button (next to the section selector) but after the docs content had been re-generated. The fix would be clearing your cache. Was this on docs-ea or the pubs?

**Comment by gfurbush** [comment]
It was on pubs.  And I did clear my cache and cookies, restarted my browser, rebooted my laptop, danced the fix-it dance, consulted with my astrologer, and threw chicken teeth at my keyboard.

**Comment by kcoleman-marklogic** [comment]
There's been no changes to what pubs is running since about a week before EA4 went live.

**Comment by dmcassel** [comment]
Ah, I didn't check pubs.
